blank_issues_enabled: true
contact_links:
  - name: Best practices for making pull requests
    url: https://discord.gg/5CceB5Y6Zt
    about: You can read more about what we expect from a pull request.

