blank_issues_enabled: true
contact_links:
  - name: Best practices for making pull requests
    url: https://docs.google.com/document/d/1Fy1-51iQSuihs6kxDCDHyGL09xRFF9U3YLX0C_r2KOA/edit?usp=sharing
    about: You can read more about what we expect from a pull request.
